{% set name = "django-excel-tools" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_excel_tools-{{ version }}.tar.gz
  sha256: 9695cc25f0582256ff83434b18864823ca526423c44fa6009353eb6e35fdb6b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-git-version
    - pip
  run:
    - python >=3.8
    - django >=3.1
    - openpyxl >=3.0.4

test:
  imports:
    - django_excel_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NorakGithub/django-excel-tools
  summary: Common function when working with excel.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
